/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package client.model;

import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Contest {
  
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("start_date")
  private Date startDate = null;
  @SerializedName("end_date")
  private Date endDate = null;
  @SerializedName("voting_start_date")
  private Date votingStartDate = null;
  @SerializedName("voting_end_date")
  private Date votingEndDate = null;
  @SerializedName("max_photos_per_user")
  private Long maxPhotosPerUser = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getStartDate() {
    return startDate;
  }
  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getEndDate() {
    return endDate;
  }
  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getVotingStartDate() {
    return votingStartDate;
  }
  public void setVotingStartDate(Date votingStartDate) {
    this.votingStartDate = votingStartDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getVotingEndDate() {
    return votingEndDate;
  }
  public void setVotingEndDate(Date votingEndDate) {
    this.votingEndDate = votingEndDate;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(value = "")
  public Long getMaxPhotosPerUser() {
    return maxPhotosPerUser;
  }
  public void setMaxPhotosPerUser(Long maxPhotosPerUser) {
    this.maxPhotosPerUser = maxPhotosPerUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contest contest = (Contest) o;
    return (this.id == null ? contest.id == null : this.id.equals(contest.id)) &&
        (this.name == null ? contest.name == null : this.name.equals(contest.name)) &&
        (this.startDate == null ? contest.startDate == null : this.startDate.equals(contest.startDate)) &&
        (this.endDate == null ? contest.endDate == null : this.endDate.equals(contest.endDate)) &&
        (this.votingStartDate == null ? contest.votingStartDate == null : this.votingStartDate.equals(contest.votingStartDate)) &&
        (this.votingEndDate == null ? contest.votingEndDate == null : this.votingEndDate.equals(contest.votingEndDate)) &&
        (this.maxPhotosPerUser == null ? contest.maxPhotosPerUser == null : this.maxPhotosPerUser.equals(contest.maxPhotosPerUser));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.endDate == null ? 0: this.endDate.hashCode());
    result = 31 * result + (this.votingStartDate == null ? 0: this.votingStartDate.hashCode());
    result = 31 * result + (this.votingEndDate == null ? 0: this.votingEndDate.hashCode());
    result = 31 * result + (this.maxPhotosPerUser == null ? 0: this.maxPhotosPerUser.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contest {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  endDate: ").append(endDate).append("\n");
    sb.append("  votingStartDate: ").append(votingStartDate).append("\n");
    sb.append("  votingEndDate: ").append(votingEndDate).append("\n");
    sb.append("  maxPhotosPerUser: ").append(maxPhotosPerUser).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
