/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package client.model;

import java.net.URI;
import java.util.Date;
import java.util.UUID;
import client.model.StatusEnum;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PatchedPhoto {
  
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("image")
  private URI image = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("owner")
  private URI owner = null;
  @SerializedName("status")
  private StatusEnum status = null;
  @SerializedName("upload_date")
  private Date uploadDate = null;
  @SerializedName("votes")
  private String votes = null;
  @SerializedName("contest")
  private URI contest = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getImage() {
    return image;
  }
  public void setImage(URI image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getOwner() {
    return owner;
  }
  public void setOwner(URI owner) {
    this.owner = owner;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getUploadDate() {
    return uploadDate;
  }
  public void setUploadDate(Date uploadDate) {
    this.uploadDate = uploadDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVotes() {
    return votes;
  }
  public void setVotes(String votes) {
    this.votes = votes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getContest() {
    return contest;
  }
  public void setContest(URI contest) {
    this.contest = contest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchedPhoto patchedPhoto = (PatchedPhoto) o;
    return (this.id == null ? patchedPhoto.id == null : this.id.equals(patchedPhoto.id)) &&
        (this.image == null ? patchedPhoto.image == null : this.image.equals(patchedPhoto.image)) &&
        (this.name == null ? patchedPhoto.name == null : this.name.equals(patchedPhoto.name)) &&
        (this.owner == null ? patchedPhoto.owner == null : this.owner.equals(patchedPhoto.owner)) &&
        (this.status == null ? patchedPhoto.status == null : this.status.equals(patchedPhoto.status)) &&
        (this.uploadDate == null ? patchedPhoto.uploadDate == null : this.uploadDate.equals(patchedPhoto.uploadDate)) &&
        (this.votes == null ? patchedPhoto.votes == null : this.votes.equals(patchedPhoto.votes)) &&
        (this.contest == null ? patchedPhoto.contest == null : this.contest.equals(patchedPhoto.contest));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.owner == null ? 0: this.owner.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.uploadDate == null ? 0: this.uploadDate.hashCode());
    result = 31 * result + (this.votes == null ? 0: this.votes.hashCode());
    result = 31 * result + (this.contest == null ? 0: this.contest.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedPhoto {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  uploadDate: ").append(uploadDate).append("\n");
    sb.append("  votes: ").append(votes).append("\n");
    sb.append("  contest: ").append(contest).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
