/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * * &#x60;Pending&#x60; - Pending * &#x60;Approved&#x60; - Approved * &#x60;Rejected&#x60; - Rejected
 **/
@ApiModel(description = "* `Pending` - Pending * `Approved` - Approved * `Rejected` - Rejected")
public class StatusEnum {
  


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusEnum statusEnum = (StatusEnum) o;
    return true;
  }

  @Override
  public int hashCode() {
    int result = 17;
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusEnum {\n");
    
    sb.append("}\n");
    return sb.toString();
  }
}
