# Generated by Django 5.2 on 2025-04-21 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_photo_votes_alter_photo_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='submission_deadline',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='voting_period',
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='voting_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='voting_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
